#!/usr/bin/env python3
"""Evaluate a StyleGAN2-ADA snapshot with FID against a dataset or reference model."""

import argparse
import copy
import json
import sys
from datetime import datetime
from pathlib import Path
from typing import Optional, Tuple

import numpy as np
import scipy.linalg


REPO_ROOT = Path(__file__).resolve().parent
STYLEGAN_DIR = REPO_ROOT / "stylegan2-ada-pytorch"
INCEPTION_URL = "https://nvlabs-fi-cdn.nvidia.com/stylegan2-ada-pytorch/pretrained/metrics/inception-2015-12-05.pt"
DEFAULT_OUTPUT_DIR = REPO_ROOT / "evaluation"


def parse_args(argv: Optional[list[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog="evaluate_model.py",
        description=(
            "Compute FID for a StyleGAN2-ADA snapshot against either a dataset "
            "or fresh images generated by a reference model."
        )
    )
    parser.add_argument("--snapshot", required=True, help="Snapshot/model pickle to evaluate.")
    reference = parser.add_mutually_exclusive_group(required=True)
    reference.add_argument("--dataset", help="StyleGAN2-ADA dataset ZIP or image folder reference.")
    reference.add_argument("--model", help="Reference model pickle that generates the reference images.")
    parser.add_argument("--num-images", type=int, default=50000, help="Generated images per model.")
    parser.add_argument("--batch-size", type=int, default=64, help="Batch size for feature extraction.")
    parser.add_argument("--seed", type=int, default=0, help="Random seed for evaluated model generation.")
    parser.add_argument(
        "--reference-seed",
        type=int,
        default=None,
        help="Random seed for reference model generation; defaults to --seed + 1.",
    )
    parser.add_argument("--trunc", dest="truncation_psi", type=float, default=1.0)
    parser.add_argument("--noise-mode", choices=["const", "random", "none"], default="const")
    parser.add_argument("--device", default="cuda", help="Torch device, e.g. cuda or cpu.")
    parser.add_argument(
        "--workers",
        type=int,
        default=0,
        help="Dataset loader workers. Keep at 0 for ZIP datasets to avoid multiprocessing ZIP read errors.",
    )
    parser.add_argument("--output-dir", default=str(DEFAULT_OUTPUT_DIR), help="Directory for JSON evaluation outputs.")
    parser.add_argument("--json", dest="json_output", action="store_true", help="Print machine-readable JSON.")
    return parser.parse_args(argv)


def ensure_stylegan_path() -> None:
    if str(STYLEGAN_DIR) not in sys.path:
        sys.path.insert(0, str(STYLEGAN_DIR))


def frechet_distance(
    mean_a: np.ndarray,
    cov_a: np.ndarray,
    mean_b: np.ndarray,
    cov_b: np.ndarray,
) -> float:
    mean_delta = np.square(mean_a - mean_b).sum()
    cov_sqrt, _ = scipy.linalg.sqrtm(np.dot(cov_a, cov_b), disp=False)
    fid = np.real(mean_delta + np.trace(cov_a + cov_b - cov_sqrt * 2))
    return float(fid)


def load_generator(snapshot: str, device):
    ensure_stylegan_path()
    import dnnlib
    import legacy

    with dnnlib.util.open_url(snapshot) as f:
        network = legacy.load_network_pkl(f)
    return copy.deepcopy(network["G_ema"]).eval().requires_grad_(False).to(device)


def make_dataset_kwargs(dataset: str, resolution: int, use_labels: bool = False) -> dict:
    return {
        "class_name": "training.dataset.ImageFolderDataset",
        "path": dataset,
        "resolution": resolution,
        "use_labels": use_labels,
        "xflip": False,
    }


def get_detector(device, verbose: bool = True):
    ensure_stylegan_path()
    from metrics import metric_utils

    return metric_utils.get_feature_detector(
        url=INCEPTION_URL,
        device=device,
        num_gpus=1,
        rank=0,
        verbose=verbose,
    )


def compute_generator_stats(
    G,
    *,
    device,
    num_images: int,
    batch_size: int,
    seed: int,
    truncation_psi: float,
    noise_mode: str,
    verbose: bool = True,
):
    ensure_stylegan_path()
    import torch
    from metrics import metric_utils

    if G.c_dim != 0:
        raise ValueError("Conditional generators are not supported by this evaluator.")

    detector = get_detector(device=device, verbose=verbose)
    stats = metric_utils.FeatureStats(capture_mean_cov=True, max_items=num_images)
    try:
        generator = torch.Generator(device=device)
    except TypeError:
        generator = torch.Generator()
    generator.manual_seed(seed)
    G = copy.deepcopy(G).eval().requires_grad_(False).to(device)

    while not stats.is_full():
        current_batch = min(batch_size, num_images - stats.num_items)
        z = torch.randn([current_batch, G.z_dim], generator=generator, device=device)
        c = torch.zeros([current_batch, G.c_dim], device=device)

        with torch.no_grad():
            images = G(z=z, c=c, truncation_psi=truncation_psi, noise_mode=noise_mode)
            images = (images * 127.5 + 128).clamp(0, 255).to(torch.uint8)
            if images.shape[1] == 1:
                images = images.repeat([1, 3, 1, 1])
            features = detector(images, return_features=True)

        stats.append(features.cpu().numpy())
        if verbose:
            print(f"generator features items {stats.num_items}/{num_images}", flush=True)

    return stats


def dataset_loader_kwargs(device, workers: int) -> dict:
    kwargs = {"pin_memory": device.type == "cuda", "num_workers": workers}
    if workers > 0:
        kwargs["prefetch_factor"] = 2
    return kwargs


def compute_dataset_stats(
    dataset: str,
    *,
    device,
    resolution: int,
    use_labels: bool,
    workers: int,
    verbose: bool = True,
):
    ensure_stylegan_path()
    from metrics import metric_utils

    dataset_kwargs = make_dataset_kwargs(dataset, resolution=resolution, use_labels=use_labels)
    opts = metric_utils.MetricOptions(
        dataset_kwargs=dataset_kwargs,
        num_gpus=1,
        rank=0,
        device=device,
        progress=metric_utils.ProgressMonitor(verbose=verbose),
        cache=True,
    )
    return metric_utils.compute_feature_stats_for_dataset(
        opts=opts,
        detector_url=INCEPTION_URL,
        detector_kwargs={"return_features": True},
        batch_size=64,
        data_loader_kwargs=dataset_loader_kwargs(device, workers),
        capture_mean_cov=True,
    )


def stats_mean_cov(stats) -> Tuple[np.ndarray, np.ndarray]:
    return stats.get_mean_cov()


def make_output_stem(result: dict) -> str:
    reference_type = result["reference"]["type"]
    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    return f"{reference_type}-fid-{timestamp}"


def write_result_json(result: dict, *, output_dir: Path, stem: Optional[str] = None) -> Path:
    output_dir.mkdir(parents=True, exist_ok=True)
    output_stem = stem if stem is not None else make_output_stem(result)
    output_path = output_dir / f"{output_stem}.json"
    output_path.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    return output_path


def evaluate(args: argparse.Namespace) -> dict:
    if args.num_images <= 0:
        raise ValueError("--num-images must be greater than zero")
    if args.batch_size <= 0:
        raise ValueError("--batch-size must be greater than zero")

    ensure_stylegan_path()
    import torch

    device = torch.device(args.device)
    reference_seed = args.reference_seed if args.reference_seed is not None else args.seed + 1

    print(f'Loading evaluated snapshot "{args.snapshot}"...')
    evaluated_G = load_generator(args.snapshot, device=device)
    evaluated_stats = compute_generator_stats(
        evaluated_G,
        device=device,
        num_images=args.num_images,
        batch_size=args.batch_size,
        seed=args.seed,
        truncation_psi=args.truncation_psi,
        noise_mode=args.noise_mode,
    )

    if args.dataset is not None:
        print(f'Computing reference features from dataset "{args.dataset}"...')
        reference_stats = compute_dataset_stats(
            args.dataset,
            device=device,
            resolution=evaluated_G.img_resolution,
            use_labels=evaluated_G.c_dim != 0,
            workers=args.workers,
        )
        reference = {"type": "dataset", "path": args.dataset}
    else:
        print(f'Loading reference model "{args.model}"...')
        reference_G = load_generator(args.model, device=device)
        if reference_G.img_resolution != evaluated_G.img_resolution:
            raise ValueError("Reference model resolution does not match evaluated model resolution.")
        print("Computing reference features from newly generated reference-model images...")
        reference_stats = compute_generator_stats(
            reference_G,
            device=device,
            num_images=args.num_images,
            batch_size=args.batch_size,
            seed=reference_seed,
            truncation_psi=args.truncation_psi,
            noise_mode=args.noise_mode,
        )
        reference = {"type": "model", "path": args.model, "seed": reference_seed}

    eval_mean, eval_cov = stats_mean_cov(evaluated_stats)
    ref_mean, ref_cov = stats_mean_cov(reference_stats)
    fid = frechet_distance(eval_mean, eval_cov, ref_mean, ref_cov)

    return {
        "snapshot": args.snapshot,
        "reference": reference,
        "fid": fid,
        "num_images": args.num_images,
        "seed": args.seed,
        "truncation_psi": args.truncation_psi,
        "noise_mode": args.noise_mode,
    }


def main() -> None:
    args = parse_args()
    result = evaluate(args)
    output_path = write_result_json(result, output_dir=Path(args.output_dir))
    if args.json_output:
        print(json.dumps(result, indent=2))
    else:
        print(f"FID: {result['fid']:.6f}")
    print(f'Wrote evaluation JSON to "{output_path}".')


if __name__ == "__main__":
    main()
